project_id = "fipdpcitsjpqivljrktj"

[functions.get-mapbox-token]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.create-ad-checkout]
verify_jwt = false

[functions.activate-ad-campaign]
verify_jwt = false

[functions.charge-boost]
verify_jwt = false

[functions.generate-bnb-qr]
verify_jwt = false

[functions.check-bnb-payment-status]
verify_jwt = false

[functions.check-in-guest]
verify_jwt = false
