ALTER TABLE public.venue_layout_areas
  ADD COLUMN IF NOT EXISTS shape TEXT NOT NULL DEFAULT 'rect',
  ADD COLUMN IF NOT EXISTS is_decor BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE public.event_areas
  ADD COLUMN IF NOT EXISTS shape TEXT NOT NULL DEFAULT 'rect',
  ADD COLUMN IF NOT EXISTS is_decor BOOLEAN NOT NULL DEFAULT false;
